name: GitHub integration testops

on:
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: "ALLURE_JOB_RUN_ID service parameter. Leave blank."
        required: false
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME service parameter. Leave blank"
        required: false

env:
  ALLURE_RESULTS: "build/allure-results"
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}


jobs:
  run_tests_and_generate_report_v2:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Get your repository's code

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest # Ensure allure-pytest is installed

      - name: Run Pytest tests and generate Allure results
        run: |
          pytest --alluredir=allure-results # Save raw Allure data to 'allure-results' directory
        continue-on-error: true # Continue even if some tests fail, so the report can still be generated
