name: GitHub integration testops

on:
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: "ALLURE_JOB_RUN_ID service parameter. Leave blank."
        required: false
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME service parameter. Leave blank"
        required: false

env:
  ALLURE_RESULTS: "build/allure-results"
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}


jobs:
  run_tests_and_generate_report_v2:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Get your repository's code

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest # Ensure allure-pytest is installed

      - name: Install and configure allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: ${{ secrets.ALLURE_ENDPOINT }}
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: 2310680
      - name: Run pytest tests with allurectl watcher
        run: | 
          allurectl watch -- pytest --alluredir=${ALLURE_RESULTS} || true
          printenv | grep "ALLURE\|GITHUB" > env.list
          export $( allurectl job-run env)
          printenv | grep TEST_
          printenv | grep ALLURE_
          echo "Now, printing what we have in env.list"
          cat env.list
        env:
          ALLURE_RESULTS: "allure-results"
          ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}          
